# Generated by Django 4.0.3 on 2023-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='repo_link',
            new_name='expertise',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contribution_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hackathon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='issue_desc',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_impact',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_info',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='project_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
