# Generated by Django 4.0.3 on 2023-11-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_alter_customuser_contribution_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='project_url',
            field=models.CharField(default='', max_length=60),
        ),
    ]
