# Generated by Django 4.0.3 on 2023-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_alter_customuser_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_url',
            field=models.TextField(),
        ),
    ]
