# Generated by Django 4.0.3 on 2023-11-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_customuser_is_email_verified_and_more'),
        ('default', '0008_customuser_is_submitted_alter_customuser_project_url'),
    ]

    operations = [
    ]
