# Generated by Django 4.0.3 on 2023-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_merge_20231123_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_submitted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
