# Generated by Django 4.0.3 on 2023-11-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_alter_customuser_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_submitted',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
