# Generated by Django 4.0.3 on 2023-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0010_customuser_phone_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpcode', models.CharField(max_length=6)),
            ],
        ),
    ]
