# Generated by Django 4.0.3 on 2023-11-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0009_merge_20231123_2011'),
        ('default', '0011_alter_customuser_is_submitted'),
    ]

    operations = [
    ]
