# Generated by Django 4.0.3 on 2023-11-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0011_otpcode'),
        ('default', '0013_alter_customuser_contribution_url_and_more'),
    ]

    operations = [
    ]
