# Generated by Django 4.0.3 on 2023-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0014_merge_20231129_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPhoneNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=18)),
                ('FromCity', models.CharField(max_length=18)),
                ('FromCountry', models.CharField(max_length=18)),
                ('Caller', models.CharField(max_length=18)),
                ('CallerCity', models.CharField(max_length=18)),
                ('CallerCountry', models.CharField(max_length=18)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='call received time')),
            ],
        ),
    ]
