# Generated by Django 4.0.3 on 2023-12-01 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0015_incomingphoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingphoneno',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 1, 17, 59, 29, 792507)),
        ),
    ]
