# Generated by Django 4.0.3 on 2023-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0016_alter_customuser_contribution_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
