# Generated by Django 4.0.3 on 2023-12-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0016_alter_incomingphoneno_time'),
        ('default', '0017_customuser_timestamp'),
    ]

    operations = [
    ]
