# Generated by Django 4.0.3 on 2023-12-04 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0019_alter_customuser_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contribution_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='expertise',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interest',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='issue_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_url',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_impact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='project_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='incomingphoneno',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
