# Generated by Django 4.0.3 on 2023-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0020_alter_customuser_contribution_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_discord',
            field=models.BooleanField(default=False),
        ),
    ]
