# Generated by Django 4.0.3 on 2023-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0021_customuser_joined_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='source',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
