# Generated by Django 4.0.3 on 2023-12-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0021_customuser_joined_discord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coder_password',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
