# Generated by Django 4.0.3 on 2023-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0022_customuser_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.TextField(blank=True, default='', null=True))            ],
        ),
    ]
