# Generated by Django 4.0.3 on 2023-12-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0022_customuser_coder_password'),
        ('default', '0023_referer'),
    ]

    operations = [
    ]
