# Generated by Django 4.0.3 on 2023-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0024_merge_0022_customuser_coder_password_0023_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='click_source',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
